#/usr/bin/env bash

# Validates that the log files that the site generates in case of errors is empty, and
# if not, print out the contents to console, and exit in error. This should provide a
# more meaningful error than the empty one that is usually generated by E2E tests
# failing.
if [ $(ls -1q /var/local/submitty/logs/site_errors | wc -l) -ne 0 ]; then
    >&2 echo -e "Site Errors Generated!\n\nContents:"
    cat /var/local/submitty/logs/site_errors/*
    exit 1
fi
