from .base_testcase import BaseTestCase
from selenium.webdriver.common.by import By
import unittest

class TestGradingNextPrev(BaseTestCase):
    def __init__(self, testname):
        super().__init__(testname, log_in=False)
    
    @unittest.skipUnless(os.environ.get('TRAVIS_BUILD_DIR') is None, "cannot run in Travis-CI")
    def test_instructor(self):
        self.log_in(user_id="instructor", user_name="Quinn")
        self.click_class('sample')
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_homework/grading/status")]').click()
        self.driver.find_element_by_link_text("Grading Index").click()
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_homework/grading/grade?who_id=student&sort=id&direction=ASC")]').click()
        self.driver.find_element_by_id('prev-student').click()
        self.assertIn("John Smith", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('prev-ungraded-student').click()
        self.assertIn("Serenity Kshlerin", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Reece Johnson", self.driver.find_element_by_id("student_info").text)
    @unittest.skipUnless(os.environ.get('TRAVIS_BUILD_DIR') is None, "cannot run in Travis-CI")
    def test_ta(self):
        self.log_in(user_id="ta", user_name="Jill")
        self.click_class('sample')
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_homework/grading/status")]').click()
        self.driver.find_element_by_link_text("Grading Index").click()
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_homework/grading/grade?who_id=student&sort=id&direction=ASC")]').click()
        self.driver.find_element_by_id('prev-student').click()
        self.assertIn("John Smith", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('prev-ungraded-student').click()
        self.assertIn("Serenity Kshlerin", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Reece Johnson", self.driver.find_element_by_id("student_info").text)
    @unittest.skipUnless(os.environ.get('TRAVIS_BUILD_DIR') is None, "cannot run in Travis-CI")
    def test_instructor_team(self):
        self.log_in(user_id="instructor", user_name="Quinn")
        self.click_class('sample')
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_team_homework/grading/status")]').click()
        self.driver.find_element_by_link_text("Grading Index").click()
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_team_homework/grading/grade?who_id=VLVlLCOOXoivBla&sort=id&direction=ASC")]').click()
        self.driver.find_element_by_id('prev-student').click()
        self.assertIn("John Smith", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('prev-ungraded-student').click()
        self.assertIn("Serenity Kshlerin", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Reece Johnson", self.driver.find_element_by_id("student_info").text)
    @unittest.skipUnless(os.environ.get('TRAVIS_BUILD_DIR') is None, "cannot run in Travis-CI")
    def test_ta_team(self):
        self.log_in(user_id="ta", user_name="Jill")
        self.click_class('sample')
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_team_homework/grading/status")]').click()
        self.driver.find_element_by_link_text("Grading Index").click()
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_team_homework/grading/grade?who_id=VLVlLCOOXoivBla&sort=id&direction=ASC")]').click()
        self.driver.find_element_by_id('prev-student').click()
        self.assertIn("John Smith", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('prev-ungraded-student').click()
        self.assertIn("Serenity Kshlerin", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Joe Student", self.driver.find_element_by_id("student_info").text)
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("Reece Johnson", self.driver.find_element_by_id("student_info").text)
    @unittest.skipUnless(os.environ.get('TRAVIS_BUILD_DIR') is None, "cannot run in Travis-CI")
    def test_instructor_navigate_away(self):
        self.log_in(user_id="instructor", user_name="Quinn")
        self.click_class('sample')
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_homework/grading/status")]').click()
        self.driver.find_element_by_link_text("Grading Index").click()
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_homework/grading/grade?who_id=aphacker&sort=id&direction=ASC")]').click()
        self.driver.find_element_by_id('prev-student').click()
        self.assertIn("No prev assigned ungraded student found!", self.driver.find_element_by_id("messages").text)
        self.driver.find_element_by_xpath('//a[contains(@href,"/sample/gradeable/grading_homework/grading/grade?who_id=troompa&sort=id&direction=ASC")]').click()
        self.driver.find_element_by_id('next-ungraded-student').click()
        self.assertIn("No next assigned ungraded student found!", self.driver.find_element_by_id("messages").text)
if __name__ == "__main__":
    import unittest
    unittest.main()
