---
submitty_dbhost: "localhost"
submitty_port: 5432
submitty_dbuser: "submitty_dbuser"
submitty_dbuser_password: ""
submitty_course_dbuser: "submitty_course_dbuser"
submitty_course_dbuser_password: ""
submitty_timezone: "America/Los_Angeles"
submitty_submission_url: "https://REPLACE_ME"
submitty_vcs_url: ""
submitty_institution_name: ""
submitty_sysadmin_email: ""
submitty_help_url: ""
submitty_authentication_method: 1
submitty_admin_user: "" #optional
submitty_email_notification_option: "y"
submitty_email_user: ""
submitty_email_password: ""
submitty_email_sender: "submitty@myuniversity.edu"
submitty_email_reply: "submitty_do_not_reply@myuniversity.edu"
submitty_email_server: "mail.myuniversity.edu"
submitty_email_server_port: 25
submitty_email_internal_format: "example.com"

submitty_ip: 123.456.7.8