---
- name: Create submitty git directory if none exists
  ansible.builtin.file:
    path: /usr/local/submitty/GIT_CHECKOUT
    state: directory

- name: Checkout submitty git repo
  ansible.builtin.git:
    repo: "{{ submitty_repo }}"
    dest: /usr/local/submitty/GIT_CHECKOUT/Submitty
    version: "{{ submitty_repo_version }}" 
    force: yes
    update: yes

- name: Set up Apache Submitty configuration
  ansible.builtin.copy:
    src: /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/apache/submitty.conf
    dest: /etc/apache2/sites-available/submitty.conf
    remote_src: yes

# TODO change install process
- name: Run Submitty install script.
  ansible.builtin.shell: |
    echo "{{ submitty_dbhost }}
      {{ submitty_port }}
      {{ submitty_dbuser }}
      {{ submitty_dbuser_password }}
      {{ submitty_course_dbuser }}
      {{ submitty_course_dbuser_password}}
      {{ submitty_timezone }}
      {{ submitty_submission_url }}
      {{ submitty_vcs_url }}
      {{ submitty_institution_name }}
      {{ submitty_sysadmin_email }}
      {{ submitty_help_url }}
      {{ submitty_authentication_method }}
      {{ submitty_admin_user }}
      {{ submitty_email_notification_option }}
      {{ submitty_email_user }}
      {{ submitty_email_password }}
      {{ submitty_email_sender }}
      {{ submitty_email_reply }}
      {{ submitty_email_server }}
      {{ submitty_email_server_port }}
      {{ submitty_email_internal_format }}
      " | bash -p ./.setup/install_system.sh > /usr/local/submitty/install.log 2>&1
  args:
    chdir: /usr/local/submitty/GIT_CHECKOUT/Submitty
  become: yes
  become_user: root

- name: Update the PHP disabled functions
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^disable_functions = '
    line: disable_functions = popen,pclose,proc_open,chmod,php_real_logo_guid,php_egg_logo_guid,php_ini_scanned_files,php_ini_loaded_file,readlink,symlink,link,set_file_buffer,proc_close,proc_terminate,proc_get_status,proc_nice,getmyuid,getmygid,getmyinode,putenv,get_current_user,magic_quotes_runtime,set_magic_quotes_runtime,import_request_variables,ini_alter,stream_socket_server,stream_socket_accept,stream_socket_pair,stream_get_transports,stream_wrapper_restore,mb_send_mail,openlog,syslog,closelog,pfsockopen,posix_kill,apache_child_terminate,apache_get_modules,apache_get_version,apache_lookup_uri,apache_reset_timeout,apache_response_headers,virtual,system,phpinfo,exec,shell_exec,passthru,

- name: Set up Apache Submitty configuration
  ansible.builtin.copy:
    src: /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/apache/submitty.conf
    dest: /etc/apache2/sites-available/submitty.conf
    remote_src: yes

- name: Set up SSL in Apache Submitty configuration
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/submitty.conf
    regexp: <VirtualHost \*:80>
    replace: "{{ lookup('file', 'append_to_submitty.conf') }}"

- name: Add ip to the Apache Submitty configuration
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/submitty.conf
    regexp: 'Require host __your_domain__'
    replace: "Require ip {{ submitty_ip }}"

- name: Add domain to the Apache Submitty configuration
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/submitty.conf
    regexp: '__your_domain__'
    replace: "{{ submitty_url }}"

- name: Add email
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/submitty.conf
    regexp: 'ADMIN@DOMAIN.HERE'
    replace: "{{ submitty_email }}"

- name: Uncomment ServerName
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/submitty.conf
    regexp: '# ServerName'
    replace: 'ServerName'

- name: Run a2ensite submitty
  ansible.builtin.command:
    cmd: a2ensite submitty

# TODO turn off TCP for postgresql

- name: Restart service apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

# TODO Switch out id_rsa file copies for an API call to Gitlab that creates a unique key and pushes it
- name: Create submitty git directory if none exists
  ansible.builtin.file:
    path: /home/submitty_daemon/.ssh/
    state: directory
    owner: submitty_daemon
    group: submitty_daemon
    mode: 0700

- name: Set up Gitlab configuration for student submissions (id_rsa)
  ansible.builtin.copy:
    src: id_rsa
    dest: /home/submitty_daemon/.ssh/id_rsa
    owner: submitty_daemon
    group: submitty_daemon
    mode: 0600

- name: Set up Gitlab configuration for student submissions (id_rsa.pub)
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: /home/submitty_daemon/.ssh/id_rsa.pub
    owner: submitty_daemon
    group: submitty_daemon
    mode: 0640

- name: Set up Gitlab configuration for student submissions (known_hosts)
  ansible.builtin.copy:
    src: known_hosts
    dest: /home/submitty_daemon/.ssh/known_hosts
    owner: submitty_daemon
    group: submitty_daemon
    mode: 0644

# Add software needed for autograding
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 300

- name: Install support packages for Submitty
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest  # noqa package-latest
  vars:
    packages:
      - clang-format

- name: Enable submittyadmin group to have sudo privileges
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: EOF
    line: '%submittyadmin ALL=(ALL:ALL) ALL'

- name: Install pytest for grading homework
  ansible.builtin.pip:
    name: pytest
    executable: pip3.3
