"""
Automatically generate rainbow grades.

usage: python3 auto_rainbow_grades.py <semester> <course>

If the instructor chooses to supply a custom_customization.json instead of using
the web form this file will always take precedence and overwrite any customization.json
generated by the web ui.
"""

# Imports
import sys
import os
import shutil
import pwd
import json

# Constants
PROVIDED_JSON_NAME = 'custom_customization.json'

# Verify correct number of command line arguments
if len(sys.argv) != 3:
    raise Exception('You must pass 2 command line arguments')

# Get path to current file directory
dir = os.path.dirname(__file__)

# Collect other path information from configuration file
config_file = dir + '/../config/submitty.json'

if not os.path.exists(config_file):
    raise Exception('Unable to locate submitty.json configuration file')

with open(config_file, 'r') as file:
    data = json.load(file)
    install_dir = data['submitty_install_dir']
    data_dir = data['submitty_data_dir']

# Collect user information from configuration file
config_file = dir + '/../config/submitty_users.json'

if not os.path.exists(config_file):
    raise Exception('Unable to locate submitty_users.json configuration file')

with open(config_file, 'r') as file:
    data = json.load(file)
    daemon_user = data['daemon_user']

# Configure variables
semester = sys.argv[1]
course = sys.argv[2]
user = daemon_user
rainbow_grades_path = install_dir + '/GIT_CHECKOUT/RainbowGrades'
courses_path = data_dir + '/courses'

# Verify user exists
users = pwd.getpwall()

user_found = False

for item in users:
    if user in item:
        user_found = True

if user_found is False:
    raise Exception('Unable to locate the specified user {}'.format(user))

# Generate path information
rg_course_path = os.path.join(courses_path, semester, course, 'rainbow_grades')

# Verify that customization.json or custom_customization.json exist
if os.path.exists(rg_course_path + '/customization.json') or \
        os.path.exists(rg_course_path + '/' + PROVIDED_JSON_NAME):
    pass

else:
    raise Exception('Unable to find a customization file')

# If makefile does not exist then copy and configure one from the main rainbow grades
# repo
if not os.path.exists(rg_course_path + '/Makefile'):

    # Copy Makefile from master rainbow grades directory
    # to course specific directory
    print('Copying initial files')
    shutil.copyfile(rainbow_grades_path + '/SAMPLE_Makefile',
                    rg_course_path + '/Makefile')

    # Setup Makefile
    print('Configuring Makefile')
    makefile_path = os.path.join(rg_course_path, 'Makefile')

    # Read in the file
    with open(makefile_path, 'r') as file:
        filedata = file.read()

    # Replace the target strings
    filedata = filedata.replace('username', user)
    filedata = filedata.replace('/<PATH_TO_SUBMITTY_REPO>/RainbowGrades',
                                rainbow_grades_path)
    filedata = filedata.replace('submitty.cs.rpi.edu', 'localhost')
    filedata = filedata.replace('<SEMESTER>/<COURSE>', '{}/{}'.format(semester, course))

    # Write the file out again
    with open(makefile_path, 'w') as file:
        file.write(filedata)

# Determine if the instructor has provided a custom_customization.json
# If so make a copy of that and rename as 'customization.json' so it will be used
if os.path.exists(rg_course_path + '/' + PROVIDED_JSON_NAME):

    shutil.copy(rg_course_path + '/' + PROVIDED_JSON_NAME,
                rg_course_path + '/customization.json')

# Change directory to course specific directory
os.chdir(rg_course_path)

# TODO: Tell submitty to generate grade reports

# Run make pull_test (command outputs capture in cmd_output for debugging)
print('Pulling in grade reports')
cmd_output = os.popen('make pull_test').read()

# Run make
print('Compiling rainbow grades')
cmd_output = os.popen('make').read()

# Run make push_test
print('Exporting to summary_html')
cmd_output = os.popen('make push_test').read()

# Recursively update permissions for all files in the rainbow_grades directory
print('Updating permissions')
cmd_output = os.popen('chmod -R o-rwx ' + rg_course_path).read()

summary_html_path = os.path.join(courses_path,
                                 semester,
                                 course,
                                 'reports',
                                 'summary_html')
cmd_output = os.popen('chmod -R o-rwx ' + summary_html_path).read()

print('Done')
