---
- name: Submitty Course Creation
  hosts: submitty
  remote_user: ubuntu
  become: yes

  roles:
    - role: submitty_term_creation
      vars:
        semester: winter23
        semester_name: Winter 2023
        start_date: 01/02/2023
        end_date: 03/19/2023

    - role: submitty_course_creation
      vars:
        semester: winter23
        course: cptr141
        section: all
        instructor: fostjo
        firstname: John
        lastname: Foster
        email: 

    - role: submitty_course_creation
      vars:
        semester: winter23
        course: cptr142
        section: all
        instructor: carmpr
        firstname: Preston
        lastname: Carman
        email: 

    - role: submitty_course_add_instructor
      vars:
        semester: winter23
        course: cptr141
        instructor: taylad
        firstname: Adam
        lastname: Taylor
        email: 

    - role: submitty_course_add_instructor
      vars:
        semester: winter23
        course: cptr141
        instructor: fostjo
        firstname: John
        lastname: Foster
        email: 

    - role: submitty_course_add_instructor
      vars:
        semester: winter23
        course: cptr142
        instructor: carmpr
        firstname: Preston
        lastname: Carman
        email: 
