---
- name: Submitty Course Creation with User Prompts.
  hosts: submitty
  remote_user: ubuntu
  become: yes

  roles:
    - submitty_course_creation

  vars_prompt:
    - name: semester
      prompt: "SEMESTER (e.g. fall21):"
    - name: course
      prompt: "COURSE (e.g. cptr141):"
    - name: section
      prompt: "SECTION (e.g. all)"
      default: all
    - name: instructor
      prompt: "INSTRUCTOR (e.g. carmpr):"
