---
- name: Submitty Homework Creation with User Prompts.
  hosts: submitty
  remote_user: ubuntu
  become: yes

  roles:
    - service_submitty_wwu
    - submitty_homework_creation

  vars_prompt:
    - name: semester
      prompt: "Semester"
      default: "winter23"
      private: no
    - name: course_number
      prompt: "Course number"
      default: "142"
      private: no
    - name: branch
      prompt: "Branch"
      default: master
      private: no
    - name: homework
      prompt: "Homework (e.g. obj1-1pt-am)"
      private: no
