---
- name: Install Submitty
  hosts: submitty
  remote_user: ubuntu
  become: yes

  roles:
    - submitty_service

  vars_prompt:
    - name: submitty_repo
      prompt: "Which submitty repo do you want to use (e.g. git@github.com:Submitty/Submitty.git)"
      default: git@github.com:Submitty/Submitty.git

    - name: submitty_repo_version
      prompt: "Which branch would you like to do (e.g. main)"
      default: main