---
- name: Install Submitty
  hosts: submitty
  remote_user: ubuntu
  become: yes

  roles:
    - submitty_service

  vars_prompt:
    - name: submitty_repo
      prompt: "Which submitty repo do you want to use (e.g. git@github.com:Submitty/Submitty.git)"
      default: "git@github.com:Submitty/Submitty.git"

    - name: submitty_repo_version
      prompt: "Which branch would you like to do (e.g. main)"
      default: "main"

    - name: submitty_dbhost
      prompt: "Specify the db host (e.g. localhost)"
      default: "localhost"

    - name: submitty_port
      prompt: "What port do you want to use for submitty (e.g. 5432)"
      default: 5432

    - name: submitty_dbuser
      prompt: "Who is your submitty db user (e.g. submitty_dbuser)"
      default: "submitty_dbuser"
      
    - name: submitty_dbuser_password
      prompt: "What is the password for your submitty db user"
      default: ""
      private: yes

    - name: submitty_course_dbuser
      prompt: "Who is your submitty course db user (e.g. submitty_course_dbuser)"
      default: ""

    - name: submitty_course_dbuser_password
      prompt: "What is the password for your submitty course db user"
      default: ""
      private: yes

    - name: submitty_timezone
      prompt: "What is your timezone (e.g. America/Los_Angeles)"
      default: "America/Los_Angeles"

    - name: submitty_submission_url
      prompt: "What url will you use for submissions (e.g. https://submitty.university.edu)"
      default: "https://REPLACE_ME"

    - name: submitty_submission_url
      prompt: "What is the url of your vcs (e.g. https://git.univeristy.edu)"
      default: ""

    - name: submitty_institution_name
      prompt: "What is the name of your institution (e.g. University Name)"
      default: ""

    # TODO make use of this variable
    #- name: submitty_institution_url
    #  prompt: 
    #  default:

    - name: submitty_sysadmin_email
      prompt: "What is the email for your sysadmin"
      default: ""

    - name: submitty_help_url
      prompt: "What is your help url"
      default: ""

    # TODO add support for other methods (currently only supports 1)
    - name: submitty_authenticaion_method
      prompt: "What authentication method do you want to use"
      default: "1"

    # TODO this is currently optional and there needs to be a way to make use of this user
    - name: submitty_admin_user
      prompt: "Who is your admin user"
      default: ""

    - name: submitty_email_notification_option
      prompt: "Do you want to use email authenticaion (y/n)"
      default: "y"

    # TODO make an example
    - name: submitty_email_user
      prompt: "Who is your submitty email user"
      default: ""

    - name: submitty_email_password
      prompt: "What is the password for your email user"
      default: ""
      private: yes

    - name: submitty_email_sender
      prompt: "What is the email address for your submitty sender (e.g. submitty@myuniversity.edu)"
      default: "submitty@myuniversity.edu"

    - name: submitty_email_reply
      prompt: "What is the email address for your submitty reply (e.g. submitty_do_not_reply@myuniversity.edu)"
      default: "submitty_do_not_reply@myuniversity.edu"

    - name: submitty_email_server
      prompt: "What is your email server (e.g. mail.myuniversity.edu)"
      default: "mail.myuniversity.edu"

    - name: submitty_email_server_port
      prompt: "What port do you use for your email server (e.g. 25)"
      default: "25"

    - name: submitty_email_internal_format
      prompt: "What is the format for internal emails (e.g. example.com)"
      default: "example.com"