#!/bin/bash
 
# SET PARAMETERS

echo "This script takes 2 parameters (USE FULL PATH)"
echo "./grade_students <assignment_submission_path> <test_input> <test_output> <results_directory_path>"
echo ""

echo "Setting Parameters"
echo "---------------------"

assignment_submission_path="$1"
echo "Assignment submissions path set to $assignment_submission_path"
test_input_path="$2"
echo "Test_Input directory set to $test_input_path"
test_output_path="$3"
echo "Test_Output directory set to $test_output_path"
results_path="$4"
echo "Results directory set to $results_path"

bin_path="$(pwd)"
echo "Path to bin set to $bin_path"

echo ""

# EXECUTION

echo "Looking for to_be_compiled.txt in $1"
if [[ ! -f  "$assignment_submission_path/to_be_compiled.txt" ]]; then
	echo "Nothing to be compiled"
	exit
fi

echo "to_be_compiled.txt found"

while read path; do

    echo "========================================================================"
    echo "========================================================================"

    echo "PATH " $path
    x=`expr index "$path" /`
    whichassignment=${path:0:$x-1}
    rest=${path:$x:${#path}}
    x=`expr index "$rest" /`
    username=${rest:0:$x-1}
    version=${rest:$x:${#rest}}
#    echo "WHICH ASSIGNMENT = $whichassignment"
#    echo "USERNAME = $username"
#    echo "VERSION = $version"


    # make a temporary directory for each student for each submission
    tmp=`mktemp -d`
    echo "Temporary directory set to $tmp"


    submittedfiles="$assignment_submission_path/$path/*"
    echo "Copying path ($submittedfiles) to tmp directory ($tmp)"

    cp 1>/dev/null  2>&1  -r $submittedfiles $tmp || echo "ERROR: Failed to copy to temporary directory"

    echo "Copying path ($test_input_path/$whichassignment/*) to tmp directory ($tmp)"	
    cp -r $test_input_path/$whichassignment/* "$tmp" || echo "ERROR: Failed to copy to temporary directory"       

    echo "Copying path ($test_output_path/$whichassignment/*) to tmp directory ($tmp)"	
    cp -r $test_output_path/$whichassignment/* "$tmp" || echo "ERROR: Failed to copy to temporary directory"       

    submission_no="$(basename $path)"
    submission_time="$(date -r $assignment_submission_path/$path "+%F %T")"


    cd $tmp

echo "here in tmp"
ls -lta
    
    echo ""
    echo "Compile code"
    echo "-----------------"

    #clang++ -Wall *.cpp -o a.out &> .submit_compilation_output.txt
    g++ -Wall *.cpp -o a.out    &> .submit_compilation_output.txt
    compile_error_code=$?


    if [[ "$compile_error_code" -ne 0 ]] ;
    then
	echo "COMPILE ERROR CODE $compile_error_code"

	more .submit_compilation_output.txt

	rm -rf $tmp
	continue
    else
	echo "COMPILE OK"
    fi

    echo ""
    echo "Running runner"
    echo "-----------------"

	# RUN RUNNER

    "$bin_path/$whichassignment/run.out"
    runner_error_code="$?"
    if [[ "$runner_error_code" -ne 0 ]] ;
    then
	echo "RUNNER ERROR CODE $runner_error_code"
	rm -rf $tmp
	continue
    else
	echo "RUNNER OK"
    fi
    

    echo ""
    
	# RUN VALIDATOR



    echo ""
    echo "Running validator"
    echo "-----------------"
    "$bin_path/$whichassignment/validate.out" "$submission_no" "$submission_time" "$runner_error_code"
    validator_error_code="$?"
    if [[ "$validator_error_code" -ne 0 ]] ;
    then
	echo "VALIDATOR ERROR CODE $validator_error_code"
	rm -rf $tmp
	continue
    else
	echo "VALIDATOR OK"
    fi

ls -lta

	echo ""

	# Get working directory back to bin
	cd "$bin_path"

	# Make directory structure in results if it doesn't exist

	
	mkdir -p "$results_path/$path" || echo "ERROR: Could not create results path $results_path/$path"

	echo "made directory $results_path/$path" 
	echo "Copying temporary directory ($tmp) to results directory ($results_path/$path)"

	# redirects prevent complaints about no files matching these patterns
#	cp  1>/dev/null  2>&1  $tmp/test*_cout.txt $tmp/test*_cerr.txt $tmp/test*_out.txt $tmp/submission.json "$results_path/$path"
	cp  1>/dev/null  2>&1  $tmp/* "$results_path/$path"
#|| echo "ERROR: Could not copy temporary directory to results directory"




#remove temporary directory
	rm -rf $tmp

echo "finished with " $path


       break #only do first

done < "$assignment_submission_path/to_be_compiled.txt"

#rm "$assignment_submission_path/to_be_compiled.txt"


echo "ALL DONE"
