// ================================================================================
//
// NOTE: This file has strict formatting requirements because it is
//   parsed by the system_call_check.cpp helper utility.
//
//
// TO GENERATE LIST OF ALL SYSTEM CALLS:
//    grep _NR /usr/include/x86_64-linux-gnu/asm/unistd_64.h /usr/include/x86_64-linux-gnu/asm/unistd_32.h | awk '{print $2}' | sort | uniq > /tmp/x
//
// ================================================================================

void allow_system_calls(scmp_filter_ctx sc, const std::set<std::string> &categories, std::ofstream &execute_logfile) {

  // ================================================================================

  // SAFELIST : PROCESS_CONTROL
  ALLOW_SYSCALL(arch_prctl, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(modify_ldt, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(exit, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(exit_group, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(getpid, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(getppid, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(nanosleep, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(restart_syscall, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(sigaction, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(sigprocmask, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(rt_sigaction, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(rt_sigprocmask, "SAFELIST:PROCESS_CONTROL");
  ALLOW_SYSCALL(getrlimit, "SAFELIST:PROCESS_CONTROL");

  // SAFELIST : PROCESS_CONTROL_MEMORY
  ALLOW_SYSCALL(brk, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(get_thread_area, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(gettid, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(mmap, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(mmap2, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(mprotect, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(mremap, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(munmap, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(set_thread_area, "SAFELIST:PROCESS_CONTROL_MEMORY");
#ifdef __NR_memfd_create
  ALLOW_SYSCALL(memfd_create, "SAFELIST:PROCESS_CONTROL_MEMORY");
#endif
  ALLOW_SYSCALL(futex, "SAFELIST:PROCESS_CONTROL_MEMORY");
  ALLOW_SYSCALL(mincore, "SAFELIST:PROCESS_CONTROL_MEMORY");

  // RESTRICTED : PROCESS_CONTROL_MEMORY_ADVANCED
  ALLOW_SYSCALL(madvise, "RESTRICTED:PROCESS_CONTROL_MEMORY_ADVANCED");
  ALLOW_SYSCALL(mbind, "RESTRICTED:PROCESS_CONTROL_MEMORY_ADVANCED");
  ALLOW_SYSCALL(migrate_pages, "RESTRICTED:PROCESS_CONTROL_MEMORY_ADVANCED");
  ALLOW_SYSCALL(set_mempolicy, "RESTRICTED:PROCESS_CONTROL_MEMORY_ADVANCED");
  ALLOW_SYSCALL(uselib, "RESTRICTED:PROCESS_CONTROL_MEMORY_ADVANCED");
#if __NR_membarrier
  ALLOW_SYSCALL(membarrier, "RESTRICTED:PROCESS_CONTROL_MEMORY_ADVANCED");
#endif

  // RESTRICTED : PROCESS_CONTROL_NEW_PROCESS_THREAD
  ALLOW_SYSCALL(clone, "RESTRICTED:PROCESS_CONTROL_NEW_PROCESS_THREAD");
  ALLOW_SYSCALL(clone3, "RESTRICTED:PROCESS_CONTROL_NEW_PROCESS_THREAD");
  ALLOW_SYSCALL(execve, "RESTRICTED:PROCESS_CONTROL_NEW_PROCESS_THREAD");
#if __NR_execveat
  ALLOW_SYSCALL(execveat, "RESTRICTED:PROCESS_CONTROL_NEW_PROCESS_THREAD");
#endif
  ALLOW_SYSCALL(fork, "RESTRICTED:PROCESS_CONTROL_NEW_PROCESS_THREAD");
  ALLOW_SYSCALL(set_tid_address, "RESTRICTED:PROCESS_CONTROL_NEW_PROCESS_THREAD");
  ALLOW_SYSCALL(vfork, "RESTRICTED:PROCESS_CONTROL_NEW_PROCESS_THREAD");

  // SAFELIST : PROCESS_CONTROL_WAITING
  ALLOW_SYSCALL(epoll_create, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(epoll_create1, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(epoll_ctl, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(epoll_ctl_old, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(epoll_pwait, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(epoll_wait, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(epoll_wait_old, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(eventfd, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(eventfd2, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(idle, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(_newselect, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(poll, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(ppoll, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(pselect6, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(select, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(wait4, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(waitid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(waitpid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getegid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getegid32, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(geteuid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(geteuid32, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getgid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getgid32, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getgroups, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getgroups32, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getpgid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getpgrp, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getresgid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getresgid32, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getresuid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getresuid32, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getuid, "SAFELIST:PROCESS_CONTROL_WAITING");
  ALLOW_SYSCALL(getuid32, "SAFELIST:PROCESS_CONTROL_WAITING");

  // RESTRICTED : PROCESS_CONTROL_SYNCHRONIZATION
  ALLOW_SYSCALL(prctl, "RESTRICTED:PROCESS_CONTROL_SYNCHRONIZATION");
  ALLOW_SYSCALL(ptrace, "RESTRICTED:PROCESS_CONTROL_SYNCHRONIZATION");
  ALLOW_SYSCALL(quotactl, "RESTRICTED:PROCESS_CONTROL_SYNCHRONIZATION");

  // RESTRICTED : PROCESS_CONTROL_SCHEDULING
  ALLOW_SYSCALL(getcpu, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(getpriority, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(nice, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(pause, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_get_priority_max, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_get_priority_min, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_getaffinity, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_getattr, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_getparam, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_getscheduler, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_rr_get_interval, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_setaffinity, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_setattr, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_setparam, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_setscheduler, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(sched_yield, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");
  ALLOW_SYSCALL(setpriority, "RESTRICTED:PROCESS_CONTROL_SCHEDULING");

  // RESTRICTED : PROCESS_CONTROL_ADVANCED
  ALLOW_SYSCALL(getrusage, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
  ALLOW_SYSCALL(move_pages, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
  ALLOW_SYSCALL(prlimit64, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
#ifdef __NR_seccomp
  ALLOW_SYSCALL(seccomp, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
#endif
  ALLOW_SYSCALL(setrlimit, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
  ALLOW_SYSCALL(ugetrlimit, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
  ALLOW_SYSCALL(ulimit, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
#ifdef __NR_userfaultfd
  ALLOW_SYSCALL(userfaultfd, "RESTRICTED:PROCESS_CONTROL_ADVANCED");
#endif

  // RESTRICTED : PROCESS_CONTROL_GET_SET_USER_GROUP_ID
  ALLOW_SYSCALL(setfsgid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setfsgid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setfsuid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setfsuid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setgid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setgid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setgroups, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setgroups32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setpgid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setregid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setregid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setresgid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setresgid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setresuid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setresuid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setreuid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setreuid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setuid, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");
  ALLOW_SYSCALL(setuid32, "RESTRICTED:PROCESS_CONTROL_GET_SET_USER_GROUP_ID");

  // ================================================================================

  // SAFELIST : FILE_MANAGEMENT
  ALLOW_SYSCALL(access, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(faccessat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(faccessat2, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(_llseek, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(close, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(creat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(dup, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(dup2, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(dup3, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fstat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fstat64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fstatat64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fstatfs, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fstatfs64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fsync, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(ftime, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(ftruncate, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(ftruncate64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(futimesat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(getcwd, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(getdents, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(getdents64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(link, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(linkat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(lseek, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(lstat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(lstat64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(mkdir, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(mkdirat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(newfstatat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(oldfstat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(oldlstat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(oldstat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(open, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(open_by_handle_at, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(openat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(pread64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(preadv, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(pwrite64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(pwritev, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(read, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(readahead, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(readdir, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(readlink, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(readlinkat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(readv, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(stat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(stat64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(statfs, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(statfs64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(sync, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(sync_file_range, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(syncfs, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(tee, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(truncate, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(truncate64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(ustat, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(write, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(writev, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(chdir, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fchdir, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fadvise64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(fadvise64_64, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(get_robust_list, "SAFELIST:FILE_MANAGEMENT");
  ALLOW_SYSCALL(set_robust_list, "SAFELIST:FILE_MANAGEMENT");

  // RESTRICTED : FILE_MANAGEMENT_MOVE_DELETE_RENAME_FILE_DIRECTORY
  ALLOW_SYSCALL(rename, "RESTRICTED:FILE_MANAGEMENT_MOVE_DELETE_RENAME_FILE_DIRECTORY");
  ALLOW_SYSCALL(renameat, "RESTRICTED:FILE_MANAGEMENT_MOVE_DELETE_RENAME_FILE_DIRECTORY");
  ALLOW_SYSCALL(renameat2, "RESTRICTED:FILE_MANAGEMENT_MOVE_DELETE_RENAME_FILE_DIRECTORY");
  ALLOW_SYSCALL(rmdir, "RESTRICTED:FILE_MANAGEMENT_MOVE_DELETE_RENAME_FILE_DIRECTORY");
  ALLOW_SYSCALL(unlink, "RESTRICTED:FILE_MANAGEMENT_MOVE_DELETE_RENAME_FILE_DIRECTORY");
  ALLOW_SYSCALL(unlinkat, "RESTRICTED:FILE_MANAGEMENT_MOVE_DELETE_RENAME_FILE_DIRECTORY");

  // RESTRICTED : FILE_MANAGEMENT_PERMISSIONS
  ALLOW_SYSCALL(chmod, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(chown, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(chown32, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(chroot, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(fchmod, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(fchmodat, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(fchown, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(fchown32, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(fchownat, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(flock, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(lchown, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(lchown32, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(lock, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(mount, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(symlink, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(symlinkat, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(umask, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(umount, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");
  ALLOW_SYSCALL(umount2, "RESTRICTED:FILE_MANAGEMENT_PERMISSIONS");

  // RESTRICTED : FILE_MANAGEMENT_CAPABILITIES
  ALLOW_SYSCALL(capget, "RESTRICTED:FILE_MANAGEMENT_CAPABILITIES");
  ALLOW_SYSCALL(capset, "RESTRICTED:FILE_MANAGEMENT_CAPABILITIES");

  // RESTRICTED : FILE_MANAGEMENT_EXTENDED_ATTRIBUTES
  ALLOW_SYSCALL(fgetxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(flistxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(fremovexattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(fsetxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(getxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(lgetxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(listxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(llistxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(lremovexattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(lsetxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(removexattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(setxattr, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");
  ALLOW_SYSCALL(statx, "RESTRICTED:FILE_MANAGEMENT_EXTENDED_ATTRIBUTES");

  // RESTRICTED : FILE_MANAGEMENT_RARE
  ALLOW_SYSCALL(fcntl, "RESTRICTED:FILE_MANAGEMENT_RARE");
  ALLOW_SYSCALL(fcntl64, "RESTRICTED:FILE_MANAGEMENT_RARE");

  // ================================================================================

  // SAFELIST : DEVICE_MANAGEMENT
  ALLOW_SYSCALL(ioctl, "SAFELIST:DEVICE_MANAGEMENT");

  // RESTRICTED : DEVICE_MANAGEMENT_ADVANCED
  ALLOW_SYSCALL(gtty, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(io_cancel, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(io_destroy, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(io_getevents, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(io_setup, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(io_submit, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(ioperm, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(iopl, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(ioprio_get, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(ioprio_set, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL(io_uring_setup, "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED");
  ALLOW_SYSCALL_BY_NUMBER(0x3f0, "RESTRICTED:rrcall_check_presence", "RESTRICTED:DEVICE_MANAGEMENT_ADVANCED"); // Julia invokes; gets ENOSYS.

  // RESTRICTED : DEVICE_MANAGEMENT_NEW_DEVICE
  ALLOW_SYSCALL(mknod, "RESTRICTED:DEVICE_MANAGEMENT_NEW_DEVICE");
  ALLOW_SYSCALL(mknodat, "RESTRICTED:DEVICE_MANAGEMENT_NEW_DEVICE");

  // ================================================================================

  // SAFELIST : INFORMATION_MAINTENANCE
  ALLOW_SYSCALL(clock_getres, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(clock_gettime, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(clock_nanosleep, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(gettimeofday, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(oldolduname, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(olduname, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(stime, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(time, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(times, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(uname, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(utime, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(utimensat, "SAFELIST:INFORMATION_MAINTENANCE");
  ALLOW_SYSCALL(utimes, "SAFELIST:INFORMATION_MAINTENANCE");
#ifdef __NR_getrandom
  ALLOW_SYSCALL(getrandom, "SAFELIST:INFORMATION_MAINTENANCE");
#endif
  ALLOW_SYSCALL(sysinfo, "SAFELIST:INFORMATION_MAINTENANCE");

  // RESTRICTED : INFORMATION_MAINTENANCE_ADVANCED
  ALLOW_SYSCALL(personality, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(reboot, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(setdomainname, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(sethostname, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(settimeofday, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(shutdown, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(swapoff, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(swapon, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(_sysctl, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");
  ALLOW_SYSCALL(syslog, "RESTRICTED:INFORMATION_MAINTENANCE_ADVANCED");

  // FORBIDDEN : INFORMATION_MAINTENANCE_SET_TIME
  ALLOW_SYSCALL(clock_adjtime, "FORBIDDEN:INFORMATION_MAINTENANCE_SET_TIME");
  ALLOW_SYSCALL(clock_settime, "FORBIDDEN:INFORMATION_MAINTENANCE_SET_TIME");

  // ================================================================================

  // RESTRICTED : COMMUNICATIONS_AND_NETWORKING_SOCKETS_MINIMAL
  ALLOW_SYSCALL(connect, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS_MINIMAL");
  ALLOW_SYSCALL(socket, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS_MINIMAL");

  // RESTRICTED : COMMUNICATIONS_AND_NETWORKING_SOCKETS
  ALLOW_SYSCALL(accept, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(accept4, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(bind, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(getpeername, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(getsockname, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(getsockopt, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(listen, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(recvfrom, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(recvmmsg, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(recvmsg, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(sendmmsg, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(sendmsg, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(sendto, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(setsockopt, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(socketcall, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");
  ALLOW_SYSCALL(socketpair, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SOCKETS");

  // RESTRICTED : COMMUNICATIONS_AND_NETWORKING_SIGNALS
  ALLOW_SYSCALL(alarm, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timer_create, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timer_delete, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timer_getoverrun, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timer_gettime, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timer_settime, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timerfd_create, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timerfd_gettime, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(timerfd_settime, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(getitimer, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(rt_sigpending, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(rt_sigqueueinfo, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(rt_sigreturn, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(rt_sigsuspend, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(rt_sigtimedwait, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(rt_tgsigqueueinfo, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(setitimer, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(sigaltstack, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(signal, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(signalfd, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(signalfd4, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(sigpending, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(sigreturn, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(sigsuspend, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");
  ALLOW_SYSCALL(rseq, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_SIGNALS");

  // RESTRICTED : COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION
  ALLOW_SYSCALL(getpmsg, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(ipc, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(mq_getsetattr, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(mq_notify, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(mq_open, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(mq_timedreceive, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(mq_timedsend, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(mq_unlink, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(msgctl, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(msgget, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(msgrcv, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(msgsnd, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(pipe, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(pipe2, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(semctl, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(semget, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(semop, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(semtimedop, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(shmat, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(shmctl, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(shmdt, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
  ALLOW_SYSCALL(shmget, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
#ifdef __NR_bpf
  ALLOW_SYSCALL(bpf, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_INTERPROCESS_COMMUNICATION");
#endif

  // RESTRICTED : TGKILL
  ALLOW_SYSCALL(tgkill, "RESTRICTED:TGKILL");

  // RESTRICTED : COMMUNICATIONS_AND_NETWORKING_KILL
  ALLOW_SYSCALL(kill, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_KILL");
  ALLOW_SYSCALL(tkill, "RESTRICTED:COMMUNICATIONS_AND_NETWORKING_KILL");

  // RESTRICTED : UNKNOWN
  // ================================================================================
  ALLOW_SYSCALL(acct, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(add_key, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(adjtimex, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(afs_syscall, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(bdflush, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(break, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(fallocate, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(fanotify_init, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(fanotify_mark, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(fdatasync, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(get_kernel_syms, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(get_mempolicy, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(getsid, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(inotify_add_watch, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(inotify_init, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(inotify_init1, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(inotify_rm_watch, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(kcmp, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(kexec_load, "RESTRICTED:UNKNOWN");
#ifdef __NR_kexec_file_load
  ALLOW_SYSCALL(kexec_file_load, "RESTRICTED:UNKNOWN");
#endif
  ALLOW_SYSCALL(keyctl, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(lookup_dcookie, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(mlock, "RESTRICTED:UNKNOWN");
#ifdef __NR_mlock2
  ALLOW_SYSCALL(mlock2, "RESTRICTED:UNKNOWN");
#endif
  ALLOW_SYSCALL(mlockall, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(mpx, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(msync, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(munlock, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(munlockall, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(name_to_handle_at, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(nfsservctl, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(perf_event_open, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(pivot_root, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(process_vm_readv, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(process_vm_writev, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(prof, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(profil, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(putpmsg, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(request_key, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(security, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(sendfile, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(sendfile64, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(setns, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(setsid, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(sgetmask, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(splice, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(ssetmask, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(stty, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(sysfs, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(tuxcall, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(unshare, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(vhangup, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(vm86, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(vm86old, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(vmsplice, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(vserver, "RESTRICTED:UNKNOWN");
  ALLOW_SYSCALL(copy_file_range, "RESTRICTED:UNKNOWN");

  // RESTRICTED : UNKNOWN_MODULE
  ALLOW_SYSCALL(create_module, "RESTRICTED:UNKNOWN_MODULE");
  ALLOW_SYSCALL(delete_module, "RESTRICTED:UNKNOWN_MODULE");
  ALLOW_SYSCALL(finit_module, "RESTRICTED:UNKNOWN_MODULE");
  ALLOW_SYSCALL(init_module, "RESTRICTED:UNKNOWN_MODULE");
  ALLOW_SYSCALL(query_module, "RESTRICTED:UNKNOWN_MODULE");

  // RESTRICTED : UNKNOWN_REMAP_PAGES
  ALLOW_SYSCALL(remap_file_pages, "RESTRICTED:UNKNOWN_REMAP_PAGES");

  // ================================================================================
}
