---
- name: Add student to submitty users.
  ansible.builtin.expect:
    command: ./adduser.py "{{ submitty_add_user_username }}"
    chdir: /usr/local/submitty/sbin/
    echo: true
    responses:
      (?m)^User givenname: "{{ submitty_add_user_username }}"
      (?m)^User preferred name: "{{ submitty_add_user_firstname }}"
      (?m)^User familyname: "{{ submitty_add_user_lastname }}"
      (?m)^User email: "{{ submitty_add_user_email }}"
      (?m)^User password: "{{ submitty_add_user_password }}"
  become: true
  become_user: root
