<?php
define("__COURSE_CODE__", "__CREATE_COURSE__FILLIN__COURSE__");
define("__DATABASE_NAME__", "__CREATE_COURSE__FILLIN__TAGRADING_DATABASE_NAME__");
define("__SUBMISSION_SERVER__", "__CREATE_COURSE__FILLIN__TAGRADING_COURSE_FILES_LOCATION__");

