#!/bin/bash
#commit hook to limit the size of a repo
REPOS="$1"
TXN="$2"

#max size for repos in kilobytes
QUOTA="10000"
MEGS=`du -sk $REPOS | sed -r "s/^([0-9\\.]+).+/\\1/"`
if [ "$MEGS" -gt "$QUOTA" ]; then
        #send error message to stderr
        echo "Repository is over ${QUOTA}K in size" 1>&2
        exit 1;
fi
exit 0;
