#!/bin/sh

# Show commands as they're executed.


# This is part of SLOCCount, a toolsuite that counts
# source lines of code (SLOC).
# Copyright (C) 2001-2004 David A. Wheeler.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# To contact David A. Wheeler, see his website at:
#  http://www.dwheeler.com.
# 
# 

echo "Per subdir"

print_sum_subset BUILD/linux/Documentation/
print_sum_subset BUILD/linux/arch/
print_sum_subset BUILD/linux/configs/
print_sum_subset BUILD/linux/drivers/
print_sum_subset BUILD/linux/fs/
print_sum_subset BUILD/linux/ibcs/
print_sum_subset BUILD/linux/include/
print_sum_subset BUILD/linux/init/
print_sum_subset BUILD/linux/ipc/
print_sum_subset BUILD/linux/kernel/
print_sum_subset BUILD/linux/ksymoops-0.7c/
print_sum_subset BUILD/linux/lib/
print_sum_subset BUILD/linux/mm/
print_sum_subset BUILD/linux/net/
print_sum_subset BUILD/linux/pcmcia-cs-3.1.8/
print_sum_subset BUILD/linux/scripts/

echo "i386 vs. non-86"

print_sum_subset BUILD/linux/arch/
print_sum_subset BUILD/linux/arch/i386 
print_sum_subset linux/drivers/sbus/  
print_sum_subset linux/drivers/macintosh/
print_sum_subset linux/drivers/sgi/      
print_sum_subset linux/drivers/fc4/
print_sum_subset linux/drivers/nubus/
print_sum_subset linux/drivers/acorn/
print_sum_subset linux/drivers/s390/ 
print_sum_subset linux/Documentation/
print_sum_subset linux/arch          




