#!/bin/sh

# redo_licenses -- recompute licenses.

# This is part of SLOCCount, a toolsuite that counts
# source lines of code (SLOC).
# Copyright (C) 2001-2004 David A. Wheeler.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# To contact David A. Wheeler, see his website at:
#  http://www.dwheeler.com.
# 
# 

SPECS=/usr/src/redhat/SPECS
BUILD=/usr/src/redhat/BUILD

cd $BUILD
for builddir in *
do
 specfile=`cat ${builddir}/ORIGINAL_SPEC_FILE | head -1`
 specfile=${SPECS}/$specfile
 echo "builddir=${builddir}, specfile=${specfile}"
 /root/extract_license "$builddir" "$specfile" > ${builddir}/PROGRAM_LICENSE
 license=`cat ${builddir}/PROGRAM_LICENSE | head -1`
 echo "   $license"

done

