---
- name: Run the create_term script to create a term.
  ansible.builtin.command:
    cmd: ./create_term.sh --amend "{{ semester }}" "{{ semester_name }}" "{{ start_date }}" "{{ end_date }}"
    chdir: /usr/local/submitty/sbin/
  become: true
  become_user: root
  changed_when: "'Term created' in create_term_result.stdout"
  notify: Reload fpm
