---
- name: Run the create_term script to create a term.
  ansible.builtin.command:
    cmd: ./create_term.sh --amend "{{ semester }}" "{{ semester_name }}" "{{ start_date }}" "{{ end_date }}"
    chdir: /usr/local/submitty/sbin/
  become: yes
  become_user: root
  notify: Reload fpm
