#!/bin/sh
# Computes Java sloc in the listed directories.
# each directory must contain ansic_list.dat and cpp_list.dat.

# Change the following if it's the wrong place:

JAVA_DATA_ENV_FILE="/home/dwheeler/sloc/bin/java_lines_environment.dat"

# Unfortunately, USC's code fails when c_list.dat is 0-length,
# so we work around it.

# 
# This is part of SLOCCount, a toolsuite that counts
# source lines of code (SLOC).
# Copyright (C) 2001-2004 David A. Wheeler.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# To contact David A. Wheeler, see his website at:
#  http://www.dwheeler.com.
# 
# 


starting_dir=`pwd`

for dir in $@
do
 if [ -d "$dir" -a -r "${dir}/filelist" ]
 then
  cd $dir
  cp $JAVA_DATA_ENV_FILE .

  if [ -s java_list.dat ]
  then
   java_lines
   extract-count < java_outfile.dat
   mv logical.sloc java-logical.sloc
   mv physical.sloc java-physical.sloc
  else
   echo 0 > java-logical.sloc
   echo 0 > java-physical.sloc
  fi

  cd $starting_dir
 fi
done
