#!/bin/sh

# print the sum of SLOC for a subset of a package.
# The subset is specified using a regular expression.

# To use, "cd" into the package data directory (with the "_outfile.dat" files),
# then specify as the first parameter the pattern defining the subset.

# E.G.:
# cd ../data/linux
# print_sum_subset 'BUILD\/linux\/drivers\/'
#
#  will show the SLOC total for the "drivers" directory & subdirs
#  of the "linux" data subdirectory.

# This is part of SLOCCount, a toolsuite that counts
# source lines of code (SLOC).
# Copyright (C) 2001-2004 David A. Wheeler.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# To contact David A. Wheeler, see his website at:
#  http://www.dwheeler.com.
# 
# 

echo -n "$1 "
grep -h "$1" *_outfile.dat | grep '^[1-9][0-9]* [^ ]' | print_sum

