name: Ansible-Install

## Controls when the workflow will run
#on:
#  # Triggers the workflow on push or pull request events but only for the "master" branch
#  pull_request:

#temporary so it runs every push  
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ansible-lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .setup/ansible
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main


  install:
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4
      - name: Setup SSH 
        shell: bash
        run: |
          ssh-keygen -t rsa -b 4096 -C "github_ci" -N '' -f /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 localhost >> /home/runner/.ssh/known_hosts
          cat /home/runner/.ssh/id_rsa.pub >> /home/runner/.ssh/authorized_keys
          ssh -T localhost
          sudo systemctl start postgresql

      - name: Run ansible script
        shell: bash 
        run: |
          cd .setup/ansible
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -e 'ansible_user=runner' -i inventory/submitty playbooks/submitty_install.yml
      - name: Validate image
        run: curl --show-error --fail --include http://localhost/authentication/login
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: install-log
          path: /usr/local/submitty/install.log

# TODO - get this working or remove it
#  ansible-molecule:
#    runs-on: ubuntu-22.04
#    services:
#      docker:
#        image: docker:dind
#        options: --privileged
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: check docker version
#        run: docker --version
#      - name: check docker run info
#        run: systemctl status docker
#      - name: Pull Docker image
#        run: docker pull geerlingguy/docker-ubuntu2204-ansible
#      - name: Set up python 3
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.x
#      - name: Install dependencies
#        run: |
#          pip3 install ansible molecule molecule-plugins[docker]
#          pip3 install ansible-lint
#      - name: Run molecule on submitty_install role
#        run: molecule test
#        working-directory: .setup/ansible/roles/submitty_install/