name: Reorganize project board

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - edited
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed

jobs:
  reorganize-board:
    name: Reorganize project board
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Reorganize project board
        run: python .github/bin/reorganize_board/main.py
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        shell: sh
