name: First PR Open
on:
  pull_request:
    types: [opened]

jobs:
  firstPrReply:
    name: First PR Open
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Check if this is user's first PR
        id: check-first-pr
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          SIX_MONTHS_AGO=$(date -d '6 months ago' +%Y-%m-%d)
          FIRST_PR=$(gh pr list --author "$USERNAME" --state all --search "created:>=$SIX_MONTHS_AGO" --limit 1 | wc -l | xargs -I {} test {} -eq 1 && echo "false" || echo "true")
          echo "first_pr=$FIRST_PR" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.event.pull_request.user.login }}

      - name: Check for existing bot comments
        id: check-comments
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BOT_COMMENT_EXISTS=$(gh pr view "$PR_NUMBER" --json comments --jq '.comments[].body' | grep -q "Hi @$USERNAME," && echo "true" || echo "false")
          echo "bot_comment_exists=$BOT_COMMENT_EXISTS" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.event.pull_request.user.login }}

      - name: First PR Open
        if: env.bot_comment_exists == 'false' && env.first_pr == 'true'
        run: |
          JSON=$(gh pr view "$PULL_REQUEST" --json headRepository,headRepositoryOwner,headRefName)
          AUTHOR=$(jq -r '.headRepositoryOwner.login' <<< $JSON)
          REPO=$(jq -r '.headRepository.name' <<< $JSON)
          BRANCH=$(jq -r '.headRefName' <<< $JSON)
          LINK="https://github.com/$AUTHOR/$REPO/actions/workflows/ci.yml?query=branch%3A$BRANCH"
          gh pr comment "$PULL_REQUEST" --body "Hi @$USERNAME,"$'\n\n'"$(cat .github/FIRST_PR_OPEN.md | sed "s|CI_URL|$LINK|")"
        env:
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          USERNAME: ${{ github.event.pull_request.user.login }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
