name: TEST VM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install virtualbox and vagrant
        run: brew install virtualbox vagrant
      - name: Vagrant Up
        run: vagrant up
